const createJobPost = (req, res, pool) => {
  console.log('Inside createJobPost module:');
  console.log(req.body);
  const title = req.body.title.toLowerCase();
  const { postingDate } = req.body;
  const { deadline } = req.body;
  const city = req.body.city.toLowerCase();
  const state = req.body.cstate.toLowerCase();
  const country = req.body.country.toLowerCase();
  const { salary } = req.body;
  const { description } = req.body;
  const { category } = req.body;
  const companyId = parseInt(req.body.companyId, 10);

  const insertSQL = `INSERT INTO job_postings (job_title,posting_date,application_deadline,city,state,country,salary,job_description,job_category,company_id) VALUES ('${title}', '${postingDate}', '${deadline}', '${city}', '${state}', '${country}', '${salary}', '${description}', '${category}', '${companyId}')`;
  pool.query(insertSQL, (insertError, result) => {
    if (insertError) {
      console.log(insertError);
      console.log('Error in createJobPost');
      res.send('Error');
    }
    console.log(`Job Post titled: ${title} created in Table: job_postings with Autogenerated ID: ${result.insertId}`);
    res.send(`Job Post titled: ${title} created in Table: job_postings with Autogenerated ID: ${result.insertId}`);
  });
};


const listCompanyPostedJobs = (req, res, pool) => {
  console.log('Inside listCompanyPostedJobs module:');
  console.log(req.body);
  const companyId = parseInt(req.body.companyId, 10);
  const searchSQL = `SELECT * FROM job_postings where company_id = '${companyId}'`;
  pool.query(searchSQL, (searchError, result) => {
    if (searchError) {
      console.log(searchError);
      console.log('Error in listCompanyPostedJobs');
      res.send('Error');
    }
    res.send(result);
  });
};

exports.createJobPost = createJobPost;
exports.listCompanyPostedJobs = listCompanyPostedJobs;
